// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJoPObIlQ3AlcB4lZmEdh6aPOhaJNT428',
    appId: '1:43606070339:web:1937b839ef1e012e8a70f6',
    messagingSenderId: '43606070339',
    projectId: 'med-tracker-77bc3',
    authDomain: 'med-tracker-77bc3.firebaseapp.com',
    storageBucket: 'med-tracker-77bc3.firebasestorage.app',
    measurementId: 'G-PT66KHV4FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh2kw99nGXX6v-0kaWaTYOJ6NMWLYcJfQ',
    appId: '1:43606070339:android:41154262dd9ec5a58a70f6',
    messagingSenderId: '43606070339',
    projectId: 'med-tracker-77bc3',
    storageBucket: 'med-tracker-77bc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVZpUNlfdifxsATuEQoIoIxTr8vrBdqj0',
    appId: '1:43606070339:ios:0f3339ddc0edb7af8a70f6',
    messagingSenderId: '43606070339',
    projectId: 'med-tracker-77bc3',
    storageBucket: 'med-tracker-77bc3.firebasestorage.app',
    androidClientId: '43606070339-7nldhumo6dfqonkli5r6sf3omcpe0qhj.apps.googleusercontent.com',
    iosClientId: '43606070339-jm81kkv79448ifim1qh3jrm984ltaja5.apps.googleusercontent.com',
    iosBundleId: 'com.example.medTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVZpUNlfdifxsATuEQoIoIxTr8vrBdqj0',
    appId: '1:43606070339:ios:0f3339ddc0edb7af8a70f6',
    messagingSenderId: '43606070339',
    projectId: 'med-tracker-77bc3',
    storageBucket: 'med-tracker-77bc3.firebasestorage.app',
    androidClientId: '43606070339-7nldhumo6dfqonkli5r6sf3omcpe0qhj.apps.googleusercontent.com',
    iosClientId: '43606070339-jm81kkv79448ifim1qh3jrm984ltaja5.apps.googleusercontent.com',
    iosBundleId: 'com.example.medTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJoPObIlQ3AlcB4lZmEdh6aPOhaJNT428',
    appId: '1:43606070339:web:ce02266424bdad8d8a70f6',
    messagingSenderId: '43606070339',
    projectId: 'med-tracker-77bc3',
    authDomain: 'med-tracker-77bc3.firebaseapp.com',
    storageBucket: 'med-tracker-77bc3.firebasestorage.app',
    measurementId: 'G-C72Y7DTLX6',
  );
}
